language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - AUTOMATED_TESTING=1
  - AUTHOR_TESTING=1
  - RELEASE_TESTING=1
install:
  - cpanm -n IO::Socket::SSL Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
  - prove -lr xt
sudo: false
